<?php

function customui_menu()
{
    $query = "select nid from node where type='menu'";
    $records = db_query($query);
    $items = array();
    $page_arguments = array();
    foreach ($records as $record) {
        $node = node_load($record->nid);
        if (!empty($node->field_page_arguments['und'])) {
            $page_arguments = explode(",", $node->field_page_arguments['und'][0]['value']);
        }
        $items[$node->field_url['und'][0]['value']] = array(
            'title' => $node->title,
            'access callback' => TRUE,
            'page callback' => $node->field_page_callback['und'][0]['value'],
            'page arguments' => $page_arguments,
            'file' => $node->field_file['und'][0]['value'],
        );
    }
    return $items;
}

function customui_theme()
{
    return array(
        'user_register_form' => array(
            'render element' => 'form',
            'template' => 'user-register-form',
            'path' => 'sites/all/modules/custom/customui/views/forms'
        ),
        'facility_node_form' => array(
            'render element' => 'form',
            'template' => 'facility-node-form',
            'path' => 'sites/all/modules/custom/customui/views/forms'
        ),
        'photo_node_form' => array(
            'render element' => 'form',
            'template' => 'photo-node-form',
            'path' => 'sites/all/modules/custom/customui/views/forms'
        ),
        'listing-view-list' => array(
            'template' => 'listing-view-list',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/listing'
        ),
        'listing-view-item' => array(
            'template' => 'listing-view-item',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/listing'
        ),
        'listing-view-item-body' => array(
            'template' => 'listing-view-item-body',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/listing'
        ),
        'listing-node-form-basic-info' => array(
            'template' => 'listing-node-form-basic-info',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/listing'
        ),
        'listing-node-form-body' => array(
            'template' => 'listing-node-form-body',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/listing'
        ),
        'about' => array(
            'template' => 'about',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/listing'
        ),
        'review' => array(
            'template' => 'review',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views'
        ),
        'facility' => array(
            'template' => 'facility',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views'
        ),
        'gallery' => array(
            'template' => 'gallery',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views'
        ),
        'location' => array(
            'template' => 'location',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views'
        ),
        'welcome' => array(
            'template' => 'welcome',
            'path' => 'sites/all/modules/custom/customui/views',
            'variables' => array('title' => '', 'contents' => array())
        ),
        'register' => array(
            'template' => 'register',
            'path' => 'sites/all/modules/custom/customui/views',
            'variables' => array('title' => '', 'contents' => array())
        ),

    );
}

function customui_listing_node_form_submit(&$form, &$form_state)
{
    $form_state['redirect'] = "listing-view";
}
function customui_facility_node_form_submit(&$form, &$form_state)
{

    $nid = empty($_GET['nid']) ? "" : $_GET['nid'];
    $form_state['redirect'] = array("facility",
        array(
            'query'=>array(
                'iframe'=>'1',
                'nid'=>$nid
            )
        ));
}
function customui_photo_node_form_submit(&$form, &$form_state)
{

    $nid = empty($_GET['nid']) ? "" : $_GET['nid'];
    $form_state['redirect'] = array("gallery",
        array(
            'query'=>array(
                'iframe'=>'1',
                'nid'=>$nid
            )
        ));
}

function customui_form_alter(&$form, &$form_state, $form_id){

    switch($form_id){
        case "listing_node_form":
            $form['actions']['submit']['#submit'][] = 'customui_listing_node_form_submit';
            $request=request_path();
            if($request=='about'){

                $form["body"]['#access'] = 1;
            }
            break;
        case "facility_node_form":
            $form['actions']['submit']['#submit'][] = 'customui_facility_node_form_submit';
            break;
        case "photo_node_form":
            $form['actions']['submit']['#submit'][] = 'customui_photo_node_form_submit';
            break;
    }
}