<?php

function customui_menu()
{
    $query = "select nid from node where type='menu'";
    $records = db_query($query);
    $items = array();
    $page_arguments = array();
    foreach ($records as $record) {
        $node = node_load($record->nid);
        if (!empty($node->field_page_arguments['und'])) {
            $page_arguments = explode(",", $node->field_page_arguments['und'][0]['value']);
        }
        $items[$node->field_url['und'][0]['value']] = array(
            'title' => $node->title,
            'access callback' => TRUE,
            'page callback' => $node->field_page_callback['und'][0]['value'],
            'page arguments' => $page_arguments,
            'file' => $node->field_file['und'][0]['value'],
        );
    }
    return $items;
}

function customui_theme()
{
    return array(
        'user_register_form' => array(
            'render element' => 'form',
            'template' => 'user-register-form',
            'path' => 'sites/all/modules/custom/customui/views/forms'
        ),
        'facility_node_form' => array(
            'render element' => 'form',
            'template' => 'facility-node-form',
            'path' => 'sites/all/modules/custom/customui/views/forms'
        ),
        'photo_node_form' => array(
            'render element' => 'form',
            'template' => 'photo-node-form',
            'path' => 'sites/all/modules/custom/customui/views/forms'
        ),
        'basic-listing-node-form' => array(
            'template' => 'basic-listing-node-form',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/forms/listing'
        ),
        'about-listing-node-form' => array(
            'template' => 'about-listing-node-form',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/forms/listing'
        ),
        'about-listing-view-item' => array(
            'template' => 'about-listing-view-item',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/listing'
        ),
        'basic-listing-view-item' => array(
            'template' => 'basic-listing-view-item',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/listing'
        ),
        'location-listing-view-item' => array(
            'template' => 'location-listing-view-item',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/listing'
        ),
        'listing-view' => array(
            'template' => 'listing-view',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/listing'
        ),
        'owner-listing-list' => array(
            'template' => 'owner-listing-list',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/listing'
        ),
        'listing-list' => array(
            'template' => 'listing-list',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/listing'
        ),
        'review' => array(
            'template' => 'review',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views'
        ),
        'facility' => array(
            'template' => 'facility',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views'
        ),
        'visitor-photo-gallery' => array(
            'template' => 'visitor-photo-gallery',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/visitor'
        ),
        'visitor-video-gallery' => array(
            'template' => 'visitor-video-gallery',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/visitor'
        ),
        'listing-photo-gallery' => array(
            'template' => 'listing-photo-gallery',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/listing'
        ),
        'listing-video-gallery' => array(
            'template' => 'visitor-video-gallery',
            'variables' => array('title' => '', 'contents' => array()),
            'path' => 'sites/all/modules/custom/customui/views/listing'
        ),
        'welcome' => array(
            'template' => 'welcome',
            'path' => 'sites/all/modules/custom/customui/views',
            'variables' => array('title' => '', 'contents' => array())
        ),
        'register' => array(
            'template' => 'register',
            'path' => 'sites/all/modules/custom/customui/views',
            'variables' => array('title' => '', 'contents' => array())
        ),
        'visitor-account' => array(
            'template' => 'visitor-account',
            'path' => 'sites/all/modules/custom/customui/views/visitor',
            'variables' => array('title' => '', 'contents' => array())
        ),

    );
}

function customui_listing_node_form_submit(&$form, &$form_state)
{
    $request_path = request_path();
    $nid = empty($_GET['nid']) ? "" : $_GET['nid'];
    switch ($request_path) {
        case "basic-listing-node-form":
            if ($nid != "") {
                $form_state['redirect'] = array("basic-listing-view-item", array(
                    'query' => array(
                        "nid" => $nid,
                        'iframe' => '1',
                    ),
                ));
            } else {
                $form_state['redirect'] = "owner-listing-list";
            }
            break;
        case "about-listing-node-form":
            if ($nid != "") {
                $form_state['redirect'] = array("about-listing-view-item", array(
                    'query' => array(
                        "nid" => $nid,
                        'iframe' => '1',
                    ),
                ));
            } else {
                $form_state['redirect'] = "owner-listing-list";
            }
            break;
        default:
            $form_state['redirect'] = "owner-listing-list";
    }
}

function customui_facility_node_form_submit(&$form, &$form_state)
{

    $nid = empty($_GET['nid']) ? "" : $_GET['nid'];
    $form_state['redirect'] = array("facility",
        array(
            'query' => array(
                'iframe' => '1',
                'nid' => $nid
            )
        ));
}

function customui_photo_node_form_submit(&$form, &$form_state)
{

    $nid = empty($_GET['nid']) ? "" : $_GET['nid'];
    $form_state['redirect'] = array("photo-gallery",
        array(
            'query' => array(
                'iframe' => '1',
                'nid' => $nid
            )
        ));
}

function customui_photo_node_form_validate(&$form, &$form_state)
{
    $nid = empty($_GET['nid']) ? "" : $_GET['nid'];
    $form_state['values']['field_node']['und']['0']['target_id'] = $nid;
}

function customui_facility_node_form_validate(&$form, &$form_state)
{
    $nid = empty($_GET['nid']) ? "" : $_GET['nid'];
    $form_state['values']['field_listing']['und']['0']['target_id'] = $nid;
}

function customui_form_alter(&$form, &$form_state, $form_id)
{

    switch ($form_id) {
        case "listing_node_form":
            $form['actions']['submit']['#submit'][] = 'customui_listing_node_form_submit';
            break;
        case "facility_node_form":
            $form['actions']['submit']['#submit'][] = 'customui_facility_node_form_submit';
            $form['#validate'][] = 'customui_facility_node_form_validate';
            $form["field_listing"]['#access'] = 0;
            break;
        case "photo_node_form":
            $form['actions']['submit']['#submit'][] = 'customui_photo_node_form_submit';
            $form['#validate'][] = 'customui_photo_node_form_validate';
            $form["field_node"]['#access'] = 0;
            break;
    }
}

function customui_page_alter()
{
    global $user;
    $user_id = $user->uid;
}